### ISSUE TITLE
Any additional file required to run BioBERT on craft ?

### ISSUE THREAD

**Issue by xw-yao** [OntoGene/craft-st#2]
One more question if you don't mind. Just wonder is there any additional file needed to run biobert on craft? I have 2-column biobert format train dev test sets ready, while it seems I'm still missing a 'tag.txt' file. In other words, what files shall I include in the input '$NER_DIR' directory. Thank you.

**Comment by lfurrer** [comment]
Isn't `tags.txt` just the tag set, ie. the vocab of the label space?
I can't tell more from the top of my head, you probably need to reach out to the original BioBERT repo if the docs here don't answer your questions.

**Comment by xw-yao** [comment]
Yes, 'tag_set.txt', found how to generate tag_set in 'format-utils.sh'. 
Thanks.
